### PR TITLE
added new bank sparda and feature target account column in csv

### PR DESCRIPTION
**Pull request by an-dr-eas-k**
This allows easier concurrent work in spreadsheet and qif importable banking app.
* We can preconfigure the target account in a field of the csv. The content in this column is set with the 'S' tag in final qif file.
* Additionally the commit adds a csv parser for my sparda bank.

### CODE REVIEW

**Comment by niknow** [comment]
Hi Andreas,
thank you very much for your contribution! Your addition of the sparda bank is very much appreciated. Also, your idea to add the feature of reading out the target account from the csv sounds very interesting.

I'm curious though: Does the csv you download from the sparda bank actually provide you with a column for that? How does your bank know how to fill that column?

**Comment by an-dr-eas-k** [comment]
Hi Nikolai,

thanks for starting the discussion and for considering my pull request. 

Your questions: I upload my transactions to gnucash and needed a feature to preprocess all transactions and assign the target account beforehand. I do this in libreoffice. For me the initial gnucash import of 2000 transactions was a lot easier to accomplish when having the target accounts at hand before the import.

The assignment of target accounts in spread sheet is easy and a batch assignment in gnucash is not at hand.

In the meantime I changed the code slightly. Two versions of the sparda csv can exist. one with target account assigned in an additional column, and the version which reads original sparda csv files.

I could imagine, such processing would be handy for other users as well, thus we/you could provide this for the other banks too. 

I altered the sparda test. There the two csv versions are checked against, for your interest.

Cheers, Andreas

**Comment by niknow** [comment]
Hi Andreas,

thanks for the clarification. I had a hunch that you preprocess your csv. ;)

I suggest that we proceed as follows: For git reasons it would be much better if these were two separate pull requests: One pull request, which only adds the sparda bank as a bank to the old repo (without preprocessing) and another one, which adds a feature supporting pre-processing of csv. 
Since the overwhelming majority of your code is adding sparda, it would be super cool, if you could change this PR to only add the sparda bank (this can be done by adding only the sparda.py (without the last function) and the test_sparda.py (without the last line) to your commit). I could then merge this into the master branch immediately and all other users would benefit immediately from your work.

The reason why I'm concerned about merging the entire thing right now is not only git, but also the following: You are a user of sparda bank and preprocess your csv. But we have to make sure that once the sparda bank is in there, every other user of the sparda bank can still use the raw csv as provided by the bank. If I understand your code correctly, that would still work, but for no one else except yourself, line 55 of sparda.py is ever executed. In that case, it should'nt be there, because that's not so good from a software development point of view.
But on the other hand, I don't think you are the only user of sparda bank preprocessing the csv. In fact, users of other banks might do that too! So it does make sense to add a pre-processing feature, but this should'nt be done on the level of the sparda bank, but should be added to the program as a whole (and probably be controllable through the command line interface?). This might be a bit more complex, which is why I think this should be a second pull request on top of this one - but the way you implemented it for sparda is a good start for this!

**Comment by an-dr-eas-k** [comment]
as discussed, I close the request prior to creating two new requests

**Pull request closed without merging**
